{% set python_min = '3.10' %}
{% set name = "kineticstoolkit" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kineticstoolkit-{{ version }}.tar.gz
  sha256: ec5236755d26d28ac78a42aa278796914fc601eb04a24efe96a8da87f6ea4149

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - pandas
    - pyqt
    - python >={{ python_min }}
    - scikit-learn
    - scipy
    - tqdm
    - limitedinteraction
    - ezc3d >=1.5.2
    - requests
    - requests-cache
    - ffmpeg

test:
  imports:
    - kineticstoolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://kineticstoolkit.uqam.ca
  summary: An open-source python library to facilitate research in biomechanics.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - felixchenier
