{% set name = "kineticstoolkit" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kineticstoolkit-{{ version }}.tar.gz
  sha256: cd4cee30cc18501c2bc6e962f78d79f96d8eb2552f19e96e7f4ce1c47cd216a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - pandas
    - pyqt
    - python >=3.8
    - scikit-learn
    - scipy
    - requests
    - limitedinteraction
    - ffmpeg

test:
  imports:
    - kineticstoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://felixchenier.uqam.ca/kineticstoolkit
  summary: An open-source python library to facilitate research in biomechanics.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - felixchenier
