{% set name = "kineticstoolkit" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kineticstoolkit-{{ version }}.tar.gz
  sha256: 01509953eaf145a8f28c613b025062484aac8544f8725738d6af7a686866eb28

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - matplotlib-base
    - pandas
    - pyqt
    - python >=3.10
    - scikit-learn
    - scipy
    - tqdm
    - limitedinteraction
    - ezc3d >=1.5.2
    - beartype >=0.17
    - requests
    - requests-cache
    - ffmpeg

test:
  imports:
    - kineticstoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://kineticstoolkit.uqam.ca
  summary: An open-source python library to facilitate research in biomechanics.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - felixchenier
